// use CTRL + F to find the required field that you are looking for
const Fields = [
  {
    SystemName: "LIST_1",
    ShortName: "LISTID",
    LongName: "Internal Listing ID",
    DataType: "Character",
  },
  {
    SystemName: "LIST_3",
    ShortName: "ListnoMain",
    LongName: "List Number Main",
    DataType: "Int",
  },
  {
    SystemName: "LIST_5",
    ShortName: "AgentID",
    LongName: "Agent ID",
    DataType: "Character",
  },
  {
    SystemName: "LIST_8",
    ShortName: "PropType",
    LongName: "Property Type",
    DataType: "Character",
  },
  {
    SystemName: "LIST_61",
    ShortName: "SellingAgencyID",
    LongName: "Selling Agency ID",
    DataType: "Character",
  },
  {
    SystemName: "LIST_62",
    ShortName: "SellingAgentID",
    LongName: "Selling Agent ID",
    DataType: "Character",
  },
  {
    SystemName: "LIST_87",
    ShortName: "Timestamp",
    LongName: "Timestamp",
    DataType: "DateTime",
  },
  {
    SystemName: "LIST_104",
    ShortName: "PublicWebsites",
    LongName: "Display on Public Websites",
    DataType: "Character",
  },
  {
    SystemName: "LIST_105",
    ShortName: "ListingID",
    LongName: "Listing ID",
    DataType: "Character",
  },
  {
    SystemName: "LIST_106",
    ShortName: "OfficeID",
    LongName: "Office ID",
    DataType: "Character",
  },
  {
    SystemName: "LIST_132",
    ShortName: "EntryTimestamp",
    LongName: "Entry Timestamp",
    DataType: "DateTime",
  },
  {
    SystemName: "LIST_133",
    ShortName: "PicCount",
    LongName: "Picture Count",
    DataType: "Int",
  },
  {
    SystemName: "LIST_134",
    ShortName: "PicTimestamp",
    LongName: "Picture Timestamp",
    DataType: "DateTime",
  },
  {
    SystemName: "VOWList",
    ShortName: "VOWEntireListingDisplay",
    LongName: "VOWEntireListingDisplay",
    DataType: "Boolean",
  },
  {
    SystemName: "VOWAddr",
    ShortName: "VOWAddressDisplay",
    LongName: "VOWAddressDisplay",
    DataType: "Boolean",
  },
  {
    SystemName: "VOWComm",
    ShortName: "VOWConsumerComment",
    LongName: "VOWConsumerComment",
    DataType: "Boolean",
  },
  {
    SystemName: "VOWAVM",
    ShortName: "VOWAutomatedValuationDisplay",
    LongName: "VOWAutomatedValuationDisplay",
    DataType: "Boolean",
  },
  {
    SystemName: "LIST_9",
    ShortName: "",
    LongName: "Sub-Type",
    DataType: "Character",
  },
  {
    SystemName: "LIST_10",
    ShortName: "",
    LongName: "List Date",
    DataType: "Date",
  },
  {
    SystemName: "LIST_12",
    ShortName: "",
    LongName: "Sold Date",
    DataType: "Date",
  },
  {
    SystemName: "LIST_13",
    ShortName: "",
    LongName: "Under Contract Date",
    DataType: "Date",
  },
  {
    SystemName: "LIST_15",
    ShortName: "",
    LongName: "Status",
    DataType: "Character",
  },
  {
    SystemName: "LIST_16",
    ShortName: "",
    LongName: "Status Change Date",
    DataType: "Date",
  },
  {
    SystemName: "LIST_17",
    ShortName: "",
    LongName: "Withdrawal Date",
    DataType: "Date",
  },
  {
    SystemName: "LIST_18",
    ShortName: "",
    LongName: "Cancel Date",
    DataType: "Date",
  },
  {
    SystemName: "LIST_21",
    ShortName: "",
    LongName: "Original List Price",
    DataType: "Decimal",
  },
  {
    SystemName: "LIST_22",
    ShortName: "",
    LongName: "List Price",
    DataType: "Decimal",
  },
  {
    SystemName: "LIST_23",
    ShortName: "",
    LongName: "Sold Price",
    DataType: "Decimal",
  },
  {
    SystemName: "LIST_31",
    ShortName: "",
    LongName: "Street #",
    DataType: "Character",
  },
  {
    SystemName: "LIST_33",
    ShortName: "",
    LongName: "Street PreDirection",
    DataType: "Character",
  },
  {
    SystemName: "LIST_34",
    ShortName: "",
    LongName: "Street Name",
    DataType: "Character",
  },
  {
    SystemName: "LIST_35",
    ShortName: "",
    LongName: "Unit/Suite #",
    DataType: "Character",
  },
  {
    SystemName: "LIST_36",
    ShortName: "",
    LongName: "Street PostDirection",
    DataType: "Character",
  },
  {
    SystemName: "LIST_37",
    ShortName: "",
    LongName: "Street Suffix",
    DataType: "Character",
  },
  {
    SystemName: "LIST_39",
    ShortName: "",
    LongName: "City (Mailing Addr)",
    DataType: "Character",
  },
  {
    SystemName: "LIST_40",
    ShortName: "",
    LongName: "State",
    DataType: "Character",
  },
  {
    SystemName: "LIST_41",
    ShortName: "",
    LongName: "County",
    DataType: "Character",
  },
  {
    SystemName: "LIST_43",
    ShortName: "",
    LongName: "Zip Code",
    DataType: "Character",
  },
  {
    SystemName: "LIST_46",
    ShortName: "",
    LongName: "Latitude",
    DataType: "Decimal",
  },
  {
    SystemName: "LIST_47",
    ShortName: "",
    LongName: "Longitude",
    DataType: "Decimal",
  },
  {
    SystemName: "LIST_48",
    ShortName: "",
    LongName: "SqFt Documented",
    DataType: "Decimal",
  },
  {
    SystemName: "LIST_49",
    ShortName: "",
    LongName: "SqFt ATFLS",
    DataType: "Decimal",
  },
  {
    SystemName: "LIST_53",
    ShortName: "",
    LongName: "Year Built",
    DataType: "Int",
  },
  {
    SystemName: "LIST_54",
    ShortName: "",
    LongName: "Style",
    DataType: "Character",
  },
  {
    SystemName: "LIST_56",
    ShortName: "",
    LongName: "Lot Size (Front)",
    DataType: "Character",
  },
  {
    SystemName: "LIST_57",
    ShortName: "",
    LongName: "Acreage",
    DataType: "Decimal",
  },
  {
    SystemName: "LIST_64",
    ShortName: "",
    LongName: "Baths F.H",
    DataType: "Decimal",
  },
  {
    SystemName: "LIST_66",
    ShortName: "",
    LongName: "Bedrooms",
    DataType: "Int",
  },
  {
    SystemName: "LIST_67",
    ShortName: "",
    LongName: "Total Baths",
    DataType: "Decimal",
  },
  {
    SystemName: "LIST_68",
    ShortName: "",
    LongName: "Full Baths",
    DataType: "Int",
  },
  {
    SystemName: "LIST_69",
    ShortName: "",
    LongName: "Half Baths",
    DataType: "Int",
  },
  {
    SystemName: "LIST_75",
    ShortName: "",
    LongName: "Taxes (Yrly)",
    DataType: "Decimal",
  },
  {
    SystemName: "LIST_76",
    ShortName: "",
    LongName: "Tax Year",
    DataType: "Int",
  },
  {
    SystemName: "LIST_77",
    ShortName: "",
    LongName: "Subdiv/Cmplx/Comm",
    DataType: "Character",
  },
  {
    SystemName: "LIST_78",
    ShortName: "",
    LongName: "Property Description",
    DataType: "Character",
  },
  {
    SystemName: "LIST_79",
    ShortName: "",
    LongName: "Addl Parcel Numbers",
    DataType: "Character",
  },
  {
    SystemName: "LIST_80",
    ShortName: "",
    LongName: "Parcel #",
    DataType: "Character",
  },
  {
    SystemName: "LIST_82",
    ShortName: "",
    LongName: "Directions",
    DataType: "Character",
  },
  {
    SystemName: "LIST_86",
    ShortName: "",
    LongName: "School District",
    DataType: "Character",
  },
  {
    SystemName: "LIST_88",
    ShortName: "",
    LongName: "Township",
    DataType: "Character",
  },
  {
    SystemName: "LIST_89",
    ShortName: "",
    LongName: "Lot Size (Side)",
    DataType: "Character",
  },
  {
    SystemName: "LIST_90",
    ShortName: "",
    LongName: "Possession",
    DataType: "Character",
  },
  {
    SystemName: "LIST_91",
    ShortName: "",
    LongName: "Corp LimitPerAuditor",
    DataType: "Character",
  },
  {
    SystemName: "LIST_92",
    ShortName: "",
    LongName: "ATFLS Source",
    DataType: "Character",
  },
  {
    SystemName: "LIST_96",
    ShortName: "",
    LongName: "Manufactured Housing",
    DataType: "Character",
  },
  {
    SystemName: "LIST_97",
    ShortName: "",
    LongName: "Vol# / Pg#",
    DataType: "Character",
  },
  {
    SystemName: "LIST_107",
    ShortName: "",
    LongName: "Instr #",
    DataType: "Character",
  },
  {
    SystemName: "LIST_108",
    ShortName: "",
    LongName: "Comm Dev Chrg",
    DataType: "Character",
  },
  {
    SystemName: "LIST_109",
    ShortName: "",
    LongName: "Per",
    DataType: "Character",
  },
  {
    SystemName: "LIST_115",
    ShortName: "",
    LongName: "Tax District",
    DataType: "Character",
  },
  {
    SystemName: "LIST_117",
    ShortName: "",
    LongName: "Assoc/Condo Fee",
    DataType: "Decimal",
  },
  {
    SystemName: "LIST_118",
    ShortName: "",
    LongName: "Located on Floor",
    DataType: "Decimal",
  },
  {
    SystemName: "LIST_119",
    ShortName: "",
    LongName: "Garage/EnclosdSpaces",
    DataType: "Decimal",
  },
  {
    SystemName: "LIST_125",
    ShortName: "",
    LongName: "List Price/SqFt",
    DataType: "Decimal",
  },
  {
    SystemName: "LIST_127",
    ShortName: "",
    LongName: "Approx Complete Date",
    DataType: "Date",
  },
  {
    SystemName: "LIST_128",
    ShortName: "",
    LongName: "Showing Start Date",
    DataType: "Date",
  },
  {
    SystemName: "LIST_129",
    ShortName: "",
    LongName: "Off Market Date",
    DataType: "Date",
  },
  {
    SystemName: "LIST_130",
    ShortName: "",
    LongName: "Contingency Reason",
    DataType: "Character",
  },
  {
    SystemName: "LIST_137",
    ShortName: "",
    LongName: "Days On Market",
    DataType: "Character",
  },
  {
    SystemName: "LIST_147",
    ShortName: "",
    LongName: "Assessment",
    DataType: "Character",
  },
  {
    SystemName: "LIST_149",
    ShortName: "",
    LongName: "HOA/COA Y/N",
    DataType: "Character",
  },
  {
    SystemName: "LIST_150",
    ShortName: "",
    LongName: "Mid/High Rise",
    DataType: "Character",
  },
  {
    SystemName: "LIST_153",
    ShortName: "",
    LongName: "Mult Parcels/Sch Dis",
    DataType: "Character",
  },
  {
    SystemName: "LIST_154",
    ShortName: "",
    LongName: "Built Prior to 1978",
    DataType: "Character",
  },
  {
    SystemName: "LIST_156",
    ShortName: "",
    LongName: "New Construction",
    DataType: "Character",
  },
  {
    SystemName: "FEAT20131031134357113811000000",
    ShortName: "Beds UP2",
    LongName: "Bedroom Level: Beds UP2",
    DataType: "Int",
  },
  {
    SystemName: "FEAT20131031134416869381000000",
    ShortName: "Beds UP1",
    LongName: "Bedroom Level: Beds UP1",
    DataType: "Int",
  },
  {
    SystemName: "FEAT20131031134444150777000000",
    ShortName: "Beds Entry Level",
    LongName: "Bedroom Level: Beds Entry Level",
    DataType: "Int",
  },
  {
    SystemName: "FEAT20131031134459551774000000",
    ShortName: "Beds Down1",
    LongName: "Bedroom Level: Beds Down1",
    DataType: "Int",
  },
  {
    SystemName: "FEAT20131031134517878332000000",
    ShortName: "Beds Down2",
    LongName: "Bedroom Level: Beds Down2",
    DataType: "Int",
  },
  {
    SystemName: "FEAT20131031134821998262000000",
    ShortName: "Full Baths UP2",
    LongName: "Full Baths Level: Full Baths UP2",
    DataType: "Int",
  },
  {
    SystemName: "FEAT20131031134836974354000000",
    ShortName: "Full Baths UP1",
    LongName: "Full Baths Level: Full Baths UP1",
    DataType: "Int",
  },
  {
    SystemName: "FEAT20131031134945127324000000",
    ShortName: "Full B Entry Level",
    LongName: "Full Baths Level: Full B Entry Level",
    DataType: "Int",
  },
  {
    SystemName: "FEAT20131031135000425809000000",
    ShortName: "Full Baths Down1",
    LongName: "Full Baths Level: Full Baths Down1",
    DataType: "Int",
  },
  {
    SystemName: "FEAT20131031135019132019000000",
    ShortName: "Full Baths Down2",
    LongName: "Full Baths Level: Full Baths Down2",
    DataType: "Int",
  },
  {
    SystemName: "FEAT20131031135058903547000000",
    ShortName: "Half Baths UP2",
    LongName: "Half Baths Level: Half Baths UP2",
    DataType: "Int",
  },
  {
    SystemName: "FEAT20131031135110945894000000",
    ShortName: "Half Baths UP1",
    LongName: "Half Baths Level: Half Baths UP1",
    DataType: "Int",
  },
  {
    SystemName: "FEAT20131031135123740806000000",
    ShortName: "Half B Entry Level",
    LongName: "Half Baths Level: Half B Entry Level",
    DataType: "Int",
  },
  {
    SystemName: "FEAT20131031135138470707000000",
    ShortName: "Half Bath Down1",
    LongName: "Half Baths Level: Half Bath Down1",
    DataType: "Int",
  },
  {
    SystemName: "FEAT20131031135153837470000000",
    ShortName: "Half Bath Down2",
    LongName: "Half Baths Level: Half Bath Down2",
    DataType: "Int",
  },
  {
    SystemName: "FEAT20131031135153837470000000",
    ShortName: "Half Bath Down2",
    LongName: "Half Baths Level: Half Bath Down2",
    DataType: "Int",
  },
  {
    SystemName: "FEAT20131031140048567852000000",
    ShortName: "Living R UP2",
    LongName: "Living Room Level: Living R UP2",
    DataType: "Int",
  },
  {
    SystemName: "FEAT20131031140131701895000000",
    ShortName: "Living R UP1",
    LongName: "Living Room Level: Living R UP1",
    DataType: "Int",
  },
  {
    SystemName: "FEAT20131031140153757209000000",
    ShortName: "Living R Entry Level",
    LongName: "Living Room Level: Living R Entry Level",
    DataType: "Int",
  },
  {
    SystemName: "FEAT20131031140216541312000000",
    ShortName: "Living R Down1",
    LongName: "Living Room Level: Living R Down1",
    DataType: "Int",
  },
  {
    SystemName: "FEAT20131031140232172804000000",
    ShortName: "Living R Down2",
    LongName: "Living Room Level: Living R Down2",
    DataType: "Int",
  },
  {
    SystemName: "FEAT20131031140418963814000000",
    ShortName: "Dining UP2",
    LongName: "Dining Room Level: Dining UP2",
    DataType: "Int",
  },
  {
    SystemName: "FEAT20131031140444843293000000",
    ShortName: "Dining UP1",
    LongName: "Dining Room Level: Dining UP1",
    DataType: "Int",
  },
  {
    SystemName: "FEAT20131031140509246835000000",
    ShortName: "Dining Entry Level",
    LongName: "Dining Room Level: Dining Entry Level",
    DataType: "Int",
  },
  {
    SystemName: "FEAT20131031140537173314000000",
    ShortName: "Dining Down1",
    LongName: "Dining Room Level: Dining Down1",
    DataType: "Int",
  },
  {
    SystemName: "FEAT20131031140549534670000000",
    ShortName: "Dining Down2",
    LongName: "Dining Room Level: Dining Down2",
    DataType: "Int",
  },
  {
    SystemName: "FEAT20131031140614725792000000",
    ShortName: "Eating Space UP2",
    LongName: "Eating Space Level: Eating Space UP2",
    DataType: "Int",
  },
  {
    SystemName: "FEAT20131031140645953292000000",
    ShortName: "Eating Space UP1",
    LongName: "Eating Space Level: Eating Space UP1",
    DataType: "Int",
  },
  {
    SystemName: "FEAT20131031140705973358000000",
    ShortName: "Eating S Entry Level",
    LongName: "Eating Space Level: Eating S Entry Level",
    DataType: "Int",
  },
  {
    SystemName: "FEAT20131031140718923881000000",
    ShortName: "Eating Space Down1",
    LongName: "Eating Space Level: Eating Space Down1",
    DataType: "Int",
  },
  {
    SystemName: "FEAT20131031140832421454000000",
    ShortName: "Eating Space Down2",
    LongName: "Eating Space Level: Eating Space Down2",
    DataType: "Int",
  },
  {
    SystemName: "FEAT20131031141107233311000000",
    ShortName: "Family Room UP2",
    LongName: "Family Room Level: Family Room UP2",
    DataType: "Int",
  },
  {
    SystemName: "FEAT20131031141214261627000000",
    ShortName: "Family Room UP1",
    LongName: "Family Room Level: Family Room UP1",
    DataType: "Int",
  },
  {
    SystemName: "FEAT20131031141225865891000000",
    ShortName: "Family R Entry Level",
    LongName: "Family Room Level: Family R Entry Level",
    DataType: "Int",
  },
  {
    SystemName: "FEAT20131031141238697815000000",
    ShortName: "Family Room Down1",
    LongName: "Family Room Level: Family Room Down1",
    DataType: "Int",
  },
  {
    SystemName: "FEAT20131031141257752521000000",
    ShortName: "Family Room Down2",
    LongName: "Family Room Level: Family Room Down2",
    DataType: "Int",
  },
  {
    SystemName: "FEAT20131031141545678437000000",
    ShortName: "Great Room UP2",
    LongName: "Great Room Level: Great Room UP2",
    DataType: "Int",
  },
  {
    SystemName: "FEAT20131031141600281540000000",
    ShortName: "Great Room UP1",
    LongName: "Great Room Level: Great Room UP1",
    DataType: "Int",
  },
  {
    SystemName: "FEAT20131031141736542236000000",
    ShortName: "Great R Entry Level",
    LongName: "Great Room Level: Great R Entry Level",
    DataType: "Int",
  },
  {
    SystemName: "FEAT20131031141645770296000000",
    ShortName: "Great Room Down1",
    LongName: "Great Room Level: Great Room Down1",
    DataType: "Int",
  },
  {
    SystemName: "FEAT20131031141700200117000000",
    ShortName: "Great Room Down2",
    LongName: "Great Room Level: Great Room Down2",
    DataType: "Int",
  },
  {
    SystemName: "FEAT20131031141807344053000000",
    ShortName: "Rec Room UP2",
    LongName: "Rec Room Level: Rec Room UP2",
    DataType: "Int",
  },
  {
    SystemName: "FEAT20131031141820607953000000",
    ShortName: "Rec Room UP1",
    LongName: "Rec Room Level: Rec Room UP1",
    DataType: "Int",
  },
  {
    SystemName: "FEAT20131031141905211081000000",
    ShortName: "Rec Room Entry Level",
    LongName: "Rec Room Level: Rec Room Entry Level",
    DataType: "Int",
  },
  {
    SystemName: "FEAT20131031150524220420000000",
    ShortName: "Rec Room Down1",
    LongName: "Rec Room Level: Rec Room Down1",
    DataType: "Int",
  },
  {
    SystemName: "FEAT20131031150540472828000000",
    ShortName: "Rec Room Down2",
    LongName: "Rec Room Level: Rec Room Down2",
    DataType: "Int",
  },
  {
    SystemName: "FEAT20131031150020693596000000",
    ShortName: "Utility UP2",
    LongName: "Utility Space Level: Utility UP2",
    DataType: "Int",
  },
  {
    SystemName: "FEAT20131031150052780727000000",
    ShortName: "Utility UP1",
    LongName: "Utility Space Level: Utility UP1",
    DataType: "Int",
  },
  {
    SystemName: "FEAT20131031150105422017000000",
    ShortName: "Utility Entry Level",
    LongName: "Utility Space Level: Utility Entry Level",
    DataType: "Int",
  },
  {
    SystemName: "FEAT20131031150144464809000000",
    ShortName: "Utility Down1",
    LongName: "Utility Space Level: Utility Down1",
    DataType: "Int",
  },
  {
    SystemName: "FEAT20131031150158032748000000",
    ShortName: "Utility Down2",
    LongName: "Utility Space Level: Utility Down2",
    DataType: "Int",
  },
  {
    SystemName: "FEAT20131031150855076016000000",
    ShortName: "Den UP2",
    LongName: "Den Level: Den UP2",
    DataType: "Int",
  },
  {
    SystemName: "FEAT20131031150911813665000000",
    ShortName: "Den UP1",
    LongName: "Den Level: Den UP1",
    DataType: "Int",
  },
  {
    SystemName: "FEAT20131031150926084746000000",
    ShortName: "Den Entry Level",
    LongName: "Den Level: Den Entry Level",
    DataType: "Int",
  },
  {
    SystemName: "FEAT20131031150939513746000000",
    ShortName: "Den Down1",
    LongName: "Den Level: Den Down1",
    DataType: "Int",
  },
  {
    SystemName: "FEAT20131031151231841907000000",
    ShortName: "Den Down2",
    LongName: "Den Level: Den Down2",
    DataType: "Int",
  },
  {
    SystemName: "FEAT20131031133653811936000000",
    ShortName: "HOA/COA Contact Name",
    LongName: "HOA/COA Info: HOA/COA Contact Name",
    DataType: "Character",
  },
  {
    SystemName: "FEAT20131031133743914585000000",
    ShortName: "HOA/COA Contact #",
    LongName: "HOA/COA Info: HOA/COA Contact #",
    DataType: "Character",
  },
  {
    SystemName: "FEAT20131031133852561991000000",
    ShortName: "HOA/COA Transfer Fee",
    LongName: "HOA/COA Info: HOA/COA Transfer Fee",
    DataType: "Decimal",
  },
  {
    SystemName: "FEAT20131031133925404527000000",
    ShortName: "Reserve Contribution",
    LongName: "HOA/COA Info: Reserve Contribution",
    DataType: "Decimal",
  },
  {
    SystemName: "FEAT20131031211911580199000000",
    ShortName: "Accessible Features",
    LongName: "Accessible Features: Accessible Features",
    DataType: "Character",
  },
  {
    SystemName: "FEAT20131118211546698472000000",
    ShortName: "Leased Items",
    LongName: "Leased Items Y/N: Leased Items",
    DataType: "Character",
  },
  {
    SystemName: "GF20131031163910977039000000",
    ShortName: "Air Conditioning",
    LongName: "Air Conditioning",
    DataType: "Character",
  },
  {
    SystemName: "GF20131031180917214874000000",
    ShortName: "Alternate Uses",
    LongName: "Alternate Uses",
    DataType: "Character",
  },
  {
    SystemName: "GF20131031163720518336000000",
    ShortName: "Basement Description",
    LongName: "Basement Description",
    DataType: "Character",
  },
  {
    SystemName: "GF20131031164518503751000000",
    ShortName: "Cmplex/Sub Amenities",
    LongName: "Cmplex/Sub Amenities",
    DataType: "Character",
  },
  {
    SystemName: "GF20131031163800328422000000",
    ShortName: "Exterior",
    LongName: "Exterior",
    DataType: "Character",
  },
  {
    SystemName: "GF20131031163949333230000000",
    ShortName: "Exterior Amenities",
    LongName: "Exterior Amenities",
    DataType: "Character",
  },
  {
    SystemName: "GF20131031163843847660000000",
    ShortName: "Fireplace",
    LongName: "Fireplace",
    DataType: "Character",
  },
  {
    SystemName: "GF20131031163858526192000000",
    ShortName: "Heating",
    LongName: "Heating",
    DataType: "Character",
  },
  {
    SystemName: "GF20131031132956061502000000",
    ShortName: "HOA/COA Fee Includes",
    LongName: "HOA/COA Fee Includes",
    DataType: "Character",
  },
  {
    SystemName: "GF20131031164004739947000000",
    ShortName: "Interior Amenities",
    LongName: "Interior Amenities",
    DataType: "Character",
  },
  {
    SystemName: "GF20131031163930899988000000",
    ShortName: "Interior Flooring",
    LongName: "Interior Flooring",
    DataType: "Character",
  },
  {
    SystemName: "GF20131031180842524249000000",
    ShortName: "Lot Characteristics",
    LongName: "Lot Characteristics",
    DataType: "Character",
  },
  {
    SystemName: "GF20131031180825020472000000",
    ShortName: "New Financing",
    LongName: "New Financing",
    DataType: "Character",
  },
  {
    SystemName: "GF20131029000255930838000000",
    ShortName: "Parking Type",
    LongName: "Parking Type",
    DataType: "Character",
  },
  {
    SystemName: "GF20131031163825088662000000",
    ShortName: "Rooms",
    LongName: "Rooms",
    DataType: "Character",
  },
  {
    SystemName: "GF20131031181330665829000000",
    ShortName: "Tax",
    LongName: "Tax",
    DataType: "Character",
  },
  {
    SystemName: "GF20131031180857177226000000",
    ShortName: "Warranty",
    LongName: "Warranty",
    DataType: "Character",
  },
  {
    SystemName: "GF20131031163919217660000000",
    ShortName: "Windows",
    LongName: "Windows",
    DataType: "Character",
  },
  {
    SystemName: "listing_member_shortid",
    ShortName: "ListMbrShort",
    LongName: "ListingMemberShortId",
    DataType: "Character",
  },
  {
    SystemName: "colisting_member_shortid",
    ShortName: "CoListMbrShort",
    LongName: "CoListingMemberShortId",
    DataType: "Character",
  },
  {
    SystemName: "selling_member_shortid",
    ShortName: "SellMbrShort",
    LongName: "SellingMemberShortId",
    DataType: "Character",
  },
  {
    SystemName: "coselling_member_shortid",
    ShortName: "CoSellMbrShort",
    LongName: "CoSellingMemberShortId",
    DataType: "Character",
  },
  {
    SystemName: "listing_office_shortid",
    ShortName: "ListOffShort",
    LongName: "ListingOfficeShortId",
    DataType: "Character",
  },
  {
    SystemName: "selling_office_shortid",
    ShortName: "SellOffShort",
    LongName: "SellingOfficeShortId",
    DataType: "Character",
  },
  {
    SystemName: "listing_member_name",
    ShortName: "ListMbrName",
    LongName: "ListingMemberName",
    DataType: "Character",
  },
  {
    SystemName: "colisting_member_name",
    ShortName: "CoListMbrName",
    LongName: "CoListingMemberName",
    DataType: "Character",
  },
  {
    SystemName: "selling_member_name",
    ShortName: "SellMbrName",
    LongName: "SellingMemberName",
    DataType: "Character",
  },
  {
    SystemName: "coselling_member_name",
    ShortName: "CoSellMbrName",
    LongName: "CoSellingMemberName",
    DataType: "Character",
  },
  {
    SystemName: "listing_office_name",
    ShortName: "ListOfcName",
    LongName: "ListingOfficeName",
    DataType: "Character",
  },
  {
    SystemName: "selling_office_name",
    ShortName: "SellOfcName",
    LongName: "SellingOfficeName",
    DataType: "Character",
  },
  {
    SystemName: "listing_member_phone",
    ShortName: "ListMbrPhone",
    LongName: "ListingMemberPhone",
    DataType: "Character",
  },
  {
    SystemName: "colisting_member_phone",
    ShortName: "CoListMbrPhone",
    LongName: "CoListingMemberPhone",
    DataType: "Character",
  },
  {
    SystemName: "selling_member_phone",
    ShortName: "SellMbrPhone",
    LongName: "SellingMemberPhone",
    DataType: "Character",
  },
  {
    SystemName: "coselling_member_phone",
    ShortName: "CoSellMbrPhone",
    LongName: "CoSellingMemberPhone",
    DataType: "Character",
  },
  {
    SystemName: "listing_office_phone",
    ShortName: "ListOffPhone",
    LongName: "ListingOfficePhone",
    DataType: "Character",
  },
  {
    SystemName: "selling_office_phone",
    ShortName: "SellOffPhone",
    LongName: "SellingOfficePhone",
    DataType: "Character",
  },
  {
    SystemName: "listing_member_fax",
    ShortName: "ListMbrFax",
    LongName: "ListingMemberFax",
    DataType: "Character",
  },
  {
    SystemName: "colisting_member_fax",
    ShortName: "CoListMbrFax",
    LongName: "CoListingMemberFax",
    DataType: "Character",
  },
  {
    SystemName: "selling_member_fax",
    ShortName: "SellMbrFax",
    LongName: "SellingMemberFax",
    DataType: "Character",
  },
  {
    SystemName: "coselling_member_fax",
    ShortName: "CoSellMbrFax",
    LongName: "CoSellingMemberFax",
    DataType: "Character",
  },
  {
    SystemName: "listing_office_fax",
    ShortName: "ListOffFax",
    LongName: "ListingOfficeFax",
    DataType: "Character",
  },
  {
    SystemName: "selling_office_fax",
    ShortName: "SellOffFax",
    LongName: "SellingOfficeFax",
    DataType: "Character",
  },
  {
    SystemName: "listing_member_address",
    ShortName: "ListMbrAddy",
    LongName: "ListingMemberAddress",
    DataType: "Character",
  },
  {
    SystemName: "colisting_member_address",
    ShortName: "CoListMbrAddy",
    LongName: "CoListingMemberAddress",
    DataType: "Character",
  },
  {
    SystemName: "selling_member_address",
    ShortName: "SellMbrAddy",
    LongName: "SellingMemberAddress",
    DataType: "Character",
  },
  {
    SystemName: "coselling_member_address",
    ShortName: "CoSellMbrAddy",
    LongName: "CoSellingMemberAddress",
    DataType: "Character",
  },
  {
    SystemName: "listing_office_address",
    ShortName: "ListOffAddy",
    LongName: "ListingOfficeAddress",
    DataType: "Character",
  },
  {
    SystemName: "selling_office_address",
    ShortName: "SellOffAddy",
    LongName: "SellingOfficeAddress",
    DataType: "Character",
  },
  {
    SystemName: "listing_member_email",
    ShortName: "ListMbrEmail",
    LongName: "ListingMemberEmail",
    DataType: "Character",
  },
  {
    SystemName: "colisting_member_email",
    ShortName: "CoListMbrEmail",
    LongName: "CoListingMemberEmail",
    DataType: "Character",
  },
  {
    SystemName: "selling_member_email",
    ShortName: "SellMbrEmail",
    LongName: "SellingMemberEmail",
    DataType: "Character",
  },
  {
    SystemName: "coselling_member_email",
    ShortName: "CoSellMbrEmail",
    LongName: "CoSellingMemberEmail",
    DataType: "Character",
  },
  {
    SystemName: "listing_office_email",
    ShortName: "ListOffEmail",
    LongName: "ListingOfficeEmail",
    DataType: "Character",
  },
  {
    SystemName: "listing_member_url",
    ShortName: "ListMbrUrl",
    LongName: "ListingMemberUrl",
    DataType: "Character",
  },
  {
    SystemName: "colisting_member_url",
    ShortName: "CoListMbrUrl",
    LongName: "CoListingMemberUrl",
    DataType: "Character",
  },
  {
    SystemName: "selling_member_url",
    ShortName: "SellMbrUrl",
    LongName: "SellingMemberUrl",
    DataType: "Character",
  },
  {
    SystemName: "coselling_member_url",
    ShortName: "CoSellMbrUrl",
    LongName: "CoSellingMemberUrl",
    DataType: "Character",
  },
  {
    SystemName: "listing_office_url",
    ShortName: "ListOffUrl",
    LongName: "ListingOfficeUrl",
    DataType: "Character",
  },
  {
    SystemName: "selling_office_url",
    ShortName: "SellOffUrl",
    LongName: "SellingOfficeUrl",
    DataType: "Character",
  },
  {
    SystemName: "UNBRANDEDIDXVIRTUALTOUR",
    ShortName: "Unbranded (IDX) Virtual Tour",
    LongName: "UnBranded Virtual Tour",
    DataType: "Character",
  },
];
